version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        APP_ENV: local
    image: 'altoiradevexam'
    ports:
      - 8080:80
    volumes:
      - ./server:/srv/app
    depends_on: 
      - db
    environment:
      USER_NAME: 'admin'
      USER_EMAIL: 'admin@email.com'
      USER_PASSWORD: 'password'
      API_TOKEN: 'IOIFJWEOIPAUHFOAISDFJIOJIjpoiahfoisdfhoihIOHOIHAFOISDHF'
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'basedb'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql